backend/bookclub/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from books import views
from books import urls as book_urls
from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("books.urls")),
]

backend/books/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from .views import register_user
from .apiviews import (
    BookList,
    BookDetail,
    MeetingList,
    MeetingDetail,
    MeetingBookList,
    UserList,
    UserDetail,
)

urlpatterns = [
    path("meetings/", MeetingList.as_view(), name="meetings_list"),
    path("meetings/<int:pk>/", MeetingDetail.as_view(), name="meetings_detail"),
    path("meetings/<int:pk>/book/", MeetingBookList.as_view(), name="meetings_book"),
    path("books/", BookList.as_view(), name="books_list"),
    path("books/<int:pk>/", BookDetail.as_view(), name="books_detail"),
    path("users/", UserList.as_view(), name="users_list"),
    path("users/<int:pk>/", UserDetail.as_view(), name="users_detail"),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/register/", register_user, name="register"),
]
# path("books/", books_list, name="books_list"),
# path("books/<int:pk>/", books_detail, name="books_detail"),
# path("bookclubs/", bookclub_list, name="bookclub_list"),
# path("bookclubs/<int:pk>/", bookclub_detail, name="bookclub_detail"),
# path("", HomePageView.as_view(), name="home"),
# path("about/", AboutPageView.as_view(), name="about"),
# path("meetings/<int:pk>/edit/", MeetingUpdateView.as_view(), name="meeting_edit"),
# path("meetings/new/", MeetingCreateView.as_view(), name="meeting_new"),
# path("book/new/", BookCreateView.as_view(), name="book_new"),
# path("book/search", book_search, name="book_search"),
# path("book/<int:pk>/", BookDetailView.as_view(), name="book_detail"),

backend/books/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core import serializers
import django.utils.timezone

# Create your models here.
import datetime


class BookClub(models.Model):
    name = models.CharField(max_length=100, default="BookClub")
    readers = models.ManyToManyField(User, related_name="bookclubreaders")

    def __str__(self) -> str:
        return f"{self.name.capitalize()}"


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    genre = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    publication_date = models.DateField(blank=True, null=True)
    ISBN = models.CharField(max_length=100, blank=True, null=True)
    cover = models.CharField(max_length=200, blank=True, null=True)
    submitter = models.ForeignKey(
        User, related_name="submitter", on_delete=models.CASCADE, blank=True, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    bookclub = models.ManyToManyField(BookClub)
    discussed = models.BooleanField(default=False)

    @property
    def book_discussed(self):
        if self.discussed is True:
            return f"Book already discussed"
        else:
            return f"Not yet discussed"

    class Meta:
        ordering = ["-updated_at", "-created_at"]

    def __str__(self) -> str:
        return f"{self.title} by {self.author}"

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})


class Meeting(models.Model):
    meeting_date = models.DateField(default=django.utils.timezone.now)
    location = models.TextField()
    host = models.ForeignKey(User, related_name="host", on_delete=models.CASCADE)
    chooser = models.ForeignKey(
        User,
        related_name="chooser",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="book",
    )

    def __str__(self) -> str:
        meeting_text = f"{self.meeting_date} @ {self.host}"
        return meeting_text

    def get_absolute_url(self):
        return reverse("meeting_detail", kwargs={"pk": self.pk})

    @property
    def host_name(self):
        return self.host.username

    @property
    def chooser_name(self):
        return self.chooser.username

    @property
    def book_name(self):
        return f"{self.book.title} by {self.book.author}"

backend/books/forms.py
from django import forms
import datetime
from .models import Meeting, Book
from django.forms import widgets


class DateInput(forms.DateInput):
    input_type = "date"


class MeetingForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = "__all__"
        widgets = {"meeting_date": widgets.DateInput(attrs={"type": "date"})}


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"
        widgets = {"publication_date": widgets.DateInput(attrs={"type": "date"})}


class BookSearchForm(forms.Form):
    author = forms.CharField(label="Author", max_length=100)
    title = forms.CharField(label="Title", max_length=100)

backend/books/views.py
from typing import Any
from django.http import HttpResponseRedirect
from django.http import HttpResponse, Http404
from django.db.models.query import QuerySet
from django.shortcuts import render
from books.models import Meeting, Book, BookClub
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
)
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from rest_framework.permissions import AllowAny
from rest_framework.decorators import api_view, permission_classes
from rest_framework import status

from .serializers import (
    BookSerializer,
    BookClubSerializer,
    MeetingSerializer,
    UserSerializer,
)
import requests
from datetime import datetime
from .forms import MeetingForm, BookForm, BookSearchForm
import json

# Create your views here.


@api_view(["POST"])
@permission_classes([AllowAny])  # Allow access without authentication
def register_user(request):
    # Retrieve user data from the request
    username = request.data.get("username")
    password = request.data.get("password")
    email = request.data.get("email")

    if not username or not password or not email:
        return Response(
            {"error": "All fields are required."}, status=status.HTTP_400_BAD_REQUEST
        )

    # Check if the username already exists
    if User.objects.filter(username=username).exists():
        return Response(
            {"error": "Username already exists."}, status=status.HTTP_400_BAD_REQUEST
        )

    # Create and save the user
    user = User.objects.create(
        username=username,
        password=make_password(password),  # hash the password
        email=email,
    )
    user.save()

    return Response(
        {"message": "User created successfully."}, status=status.HTTP_201_CREATED
    )


@login_required
def bookclub_list(request):
    bookclubs = BookClub.objects.all()
    data = {"results": list(bookclubs.values("name"))}

    return JsonResponse(data)


@login_required
def bookclub_detail(request, pk):

    bookclub = get_object_or_404(BookClub, pk=pk)

    data = {
        "results": {
            "name": bookclub.name,
        }
    }
    return JsonResponse(data)


@login_required
def meetings_list(request):
    meetings = Meeting.objects.all()
    data = {
        "results": list(
            meetings.values(
                "meeting_date", "location", "host__username", "chooser__username"
            )
        )
    }
    return JsonResponse(data)


@login_required
def meetings_detail(request, pk):
    meeting = get_object_or_404(Meeting, pk=pk)
    chooser_username = ""
    if meeting.chooser is not None:
        chooser_username = meeting.chooser.username
    data = {
        "results": {
            "meeting_date": meeting.meeting_date,
            "location": meeting.location,
            "host": meeting.host.username,
            "chooser": chooser_username,
        }
    }
    return JsonResponse(data)


@login_required
def books_list(request):
    books = Book.objects.all()
    data = {
        "results": list(
            books.values(
                "title",
                "author",
                "genre",
                "description",
                "publication_date",
                "ISBN",
                "cover",
                "submitter__username",
                "created_at",
                "updated_at",
                "bookclub__name",
                "meeting",
            )
        )
    }
    return JsonResponse(data)


@login_required
def books_detail(request, pk):
    book = get_object_or_404(Book, pk=pk)
    print(book)
    submitter_username = ""
    if book.submitter:
        submitter_username = book.submitter.username

    data = {
        "results": {
            "title": book.title,
            "author": book.author,
            "genre": book.genre,
            "description": book.description,
            "publication_date": book.publication_date,
            "ISBN": book.ISBN,
            "cover": book.cover,
            "submitter": submitter_username,
            "created_at": book.created_at,
            "updated_at": book.updated_at,
            "bookclub": book.bookclub.name,
            "meeting": book.meeting,
        }
    }
    return JsonResponse(data)

backend/books/templates/about.html
{% extends 'base.html' %}
{% block content %}
<br>
<h2>This is the Saffron Walden Book Club</h2>

<div id="text">
<p>Meeting every 6 to 7 weeks, it is the highlight of Saffron Walden's cultural agenda. </p>

</div>

{% endblock %}

backend/books/templates/base.html
<!-- templates/base.html -->
{% load static %}   
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title >Saffron Walden Book Club</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
    
    <div class="container">
    <h1 class="text-left text-primary"> Saffron Walden Book Club</h1>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary-subtle bg-gradient">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home'  %}">SW Book Club</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home'  %}">Home</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{% url 'meetings'  %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Meetings
                    </a>
                    <ul class="dropdown-menu bg-primary-subtle bg-gradient">
                      <li><a class="dropdown-item" href="{% url 'meetings'  %}">View Meetings</a></li>
                      <li><a class="dropdown-item" href="{% url 'meeting_new' %}">Create New Meeting</a></li>

                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'book_search'  %}">Book Search</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'about'  %}">About</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                  </li>
                </ul>
                
              </div>
            </div>
          </nav>



    </header>
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

backend/books/templates/book_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <br>
    <div class="row">
    {% for book in books %}
    <div class="card" style="width: 24rem;">
        <div class="card-body">
        <img src= {{book.volumeInfo.imageLinks.thumbnail}} class="card-img-top" alt="...">
          <h5 class="card-title">{{book.volumeInfo.title}}</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">{{book.volumeInfo.authors.0}}</h6>
          <p class="card-text">{{book.volumeInfo.description}}</p>
          <a href="{%url 'book_new' %}" value="{{book}}" class="btn btn-primary"> Save Book </a>
          <form action="{% url 'book_save' %}" method="POST">
            {% csrf_token %}
        <button type ='submit' value="{{ book }}" name="book" class='btn btn-outline-info' > 
        Save </button>
           
       </form> 
        </div>
      </div>
      {% endfor %}
      </div>
{% endblock content %}

backend/books/templates/book_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{{ form.media }}
{% block content %}

<div class="container">
    <br>
    <div class="row">
          
    <div class="card" style="width: 24rem;">
        <div class="card-body">
        <img src= {{thumbnail}} class="card-img-top" alt="...">
          <h5 class="card-title">{{title}}</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">{{author}}</h6>
          <p class="card-text">{{description}}</p>
         </div>
      </div>

      </div>


<div class="container">
<h1> Add a new Book</h1>
{{ form.media }} 
<form action="" method="post">
    {% csrf_token%}
  
    {{ form|crispy}}
    <input type="submit" value="Save">
</form>

</div>

{% endblock content %}

backend/books/templates/book_search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{{ form.media }}
{% block content %}
<br>
<div class="container">
<br>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

</div>

{% endblock content %}

backend/books/templates/home.html
{% extends 'base.html' %}
{% block content %}
<br>

<div class="container">
    <p> Welcome to the Saffron Walden book club website.</p>
<p> Please find below information for the next meeting and the book to read. </p>
  <p>Use the menu above to view past and future meetings, add a book to the book club list, review books and many more!</p>  
</div>
<br>
<div class = "container">
    <h2>Next meeting:</h2>
</div>

<div id=meeting-div class = "container">
    <table class="table">
    <tr>
    <th>Date</th>
    <th>Host</th>
    <th>Location</th>
    <th>Details</th>
    </tr>
    {% for meeting in meetings %}
    <tr>
        <th>{{ meeting.meeting_date }}</th>
        <th>{{ meeting.host }}</th>
        <th>{{ meeting.location }}</th>
        <th><a href="{{ meeting.get_absolute_url }}">Show More</a></th>
    </tr>
    {% endfor %}
    </table>
    
    </div>
    {% endblock %}

backend/books/templates/meeting_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
<br>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Meeting info</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">{{meeting.meeting_date}}</h6>
          <p class="card-text">Host will be: {{meeting.host}} at {{meeting.location}}</p>
          <a href="{%url 'meeting_edit' meeting.pk %}" class="btn btn-primary"> Edit Meeting </a>
         </div>
      </div>


{% endblock content %}

backend/books/templates/meeting_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <h1> Edit Meeting</h1>
    {{ form.media }} 
    <form action="" method="post">
        {% csrf_token%}
        {{ form|crispy}}
        <input type="submit" value="Update">
    </form>
    
    </div>

{% endblock content %}

backend/books/templates/meeting_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{{ form.media }}
{% block content %}

<div class="container">
<h1> New Meeting</h1>
{{ form.media }} 
<form action="" method="post">
    {% csrf_token%}
    {{ form|crispy}}
    <input type="submit" value="Save">
</form>

</div>

{% endblock content %}

backend/books/templates/meetings.html
{% extends 'base.html' %}

{% block content %}
<br>
<div >


</div>
<div>
    <h2>Upcoming Meetings</h2>
</div>

<div id=meeting-div class = "container">
    <div class="row">
    {% for meeting in meeting_list.future_meetings %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{meeting.meeting_date}}</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">Host:  {{meeting.host}}</h6>
          <p class="card-text">Location: {{meeting.location}}</p>
          <a href="{{ meeting.get_absolute_url }}"  class="btn btn-outline-primary">Show More</a>
          <a href="{%url 'meeting_edit' meeting.pk %}"  class="btn btn-outline-primary"> Edit Meeting </a>
         </div>
      </div>
      {% endfor %}
</div>
</div>


<div>
    <h2>Past Meetings</h2>
</div>
<div id=meeting-div2 class = "container">
    <table class="table">
    <tr>
    <th>Date</th>
    <th>Host</th>
    <th>Location</th>
    <th>Details</th>
    </tr>
    {% for meeting in meeting_list.past_meetings %}
    <tr>
        <th>{{ meeting.meeting_date }}</th>
        <th>{{ meeting.host }}</th>
        <th>{{ meeting.location }}</th>
        <th><a href="{{ meeting.get_absolute_url }}">Show More</a></th>
    </tr>
    {% endfor %}
    </table>
    
    </div>

{% endblock content %}